[p2p]
listen_addr = "0.0.0.0:17986"
external_addr = "192.168.2.164:17984"
bootstrap_nodes = ["192.168.2.164:17974"]
max_connections = 100
connection_ttl_secs = 300
protocol_id = "NRCS/2.1"

[api]
host = "0.0.0.0"
port = 18196

[websocket]
enabled = true
port = 18194

[database]
url = "sqlite:///mnt/d/workspace/git/rust-nrcs/nrcs.db?mode=rwc"
max_connections = 10
