CREATE TABLE IF NOT EXISTS ACCOUNT
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 BALANCE BIGINT NOT NULL,
 UNCONFIRMED_BALANCE BIGINT NOT NULL,
 FORGED_BALANCE BIGINT NOT NULL,
 ACTIVE_LESSEE_ID BIGINT,
 HAS_CONTROL_PHASING BOOLEAN DEFAULT FALSE NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX ACCOUNT_ID_HEIGHT_IDX ON ACCOUNT (ID, HEIGHT DESC);
CREATE INDEX ACCOUNT_ACTIVE_LESSEE_ID_IDX ON ACCOUNT (ACTIVE_LESSEE_ID);
CREATE INDEX ACCOUNT_HEIGHT_ID_IDX ON ACCOUNT (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS ACCOUNT_ASSET
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 ASSET_ID BIGINT NOT NULL,
 QUANTITY BIGINT NOT NULL,
 UNCONFIRMED_QUANTITY BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX ACCOUNT_ASSET_ID_HEIGHT_IDX ON ACCOUNT_ASSET (ACCOUNT_ID, ASSET_ID, HEIGHT DESC);
CREATE INDEX ACCOUNT_ASSET_ASSET_ID_IDX ON ACCOUNT_ASSET (ASSET_ID);
CREATE INDEX ACCOUNT_ASSET_QUANTITY_IDX ON ACCOUNT_ASSET (QUANTITY DESC);
CREATE INDEX ACCOUNT_ASSET_HEIGHT_ID_IDX ON ACCOUNT_ASSET (HEIGHT, ACCOUNT_ID, ASSET_ID);
CREATE TABLE IF NOT EXISTS ACCOUNT_CONTROL_PHASING
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 WHITELIST varchar(5000),
 VOTING_MODEL SMALLINT NOT NULL,
 QUORUM BIGINT,
 MIN_BALANCE BIGINT,
 HOLDING_ID BIGINT,
 MIN_BALANCE_MODEL SMALLINT,
 MAX_FEES BIGINT,
 MIN_DURATION SMALLINT,
 MAX_DURATION SMALLINT,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX ACCOUNT_CONTROL_PHASING_ID_HEIGHT_IDX ON ACCOUNT_CONTROL_PHASING (ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX ACCOUNT_CONTROL_PHASING_HEIGHT_ID_IDX ON ACCOUNT_CONTROL_PHASING (HEIGHT, ACCOUNT_ID);
CREATE TABLE IF NOT EXISTS ACCOUNT_CURRENCY
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 CURRENCY_ID BIGINT NOT NULL,
 UNITS BIGINT NOT NULL,
 UNCONFIRMED_UNITS BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX ACCOUNT_CURRENCY_ID_HEIGHT_IDX ON ACCOUNT_CURRENCY (ACCOUNT_ID, CURRENCY_ID, HEIGHT DESC);
CREATE INDEX ACCOUNT_CURRENCY_CURRENCY_ID_IDX ON ACCOUNT_CURRENCY (CURRENCY_ID);
CREATE INDEX ACCOUNT_CURRENCY_UNITS_IDX ON ACCOUNT_CURRENCY (UNITS DESC);
CREATE INDEX ACCOUNT_CURRENCY_HEIGHT_ID_IDX ON ACCOUNT_CURRENCY (HEIGHT, ACCOUNT_ID, CURRENCY_ID);
CREATE TABLE IF NOT EXISTS ACCOUNT_FXT
(
 ID BIGINT NOT NULL,
 BALANCE BYTEA NOT NULL,
 HEIGHT INTEGER NOT NULL
);
CREATE UNIQUE INDEX ACCOUNT_FXT_ID_IDX ON ACCOUNT_FXT (ID, HEIGHT DESC);
CREATE TABLE IF NOT EXISTS ACCOUNT_GUARANTEED_BALANCE
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 ADDITIONS BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL
);
CREATE UNIQUE INDEX ACCOUNT_GUARANTEED_BALANCE_ID_HEIGHT_IDX ON ACCOUNT_GUARANTEED_BALANCE (ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX ACCOUNT_GUARANTEED_BALANCE_HEIGHT_IDX ON ACCOUNT_GUARANTEED_BALANCE (HEIGHT);
CREATE TABLE IF NOT EXISTS ACCOUNT_INFO
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 NAME varchar(5000),
 DESCRIPTION varchar(5000),
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX ACCOUNT_INFO_ID_HEIGHT_IDX ON ACCOUNT_INFO (ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX ACCOUNT_INFO_HEIGHT_ID_IDX ON ACCOUNT_INFO (HEIGHT, ACCOUNT_ID);
CREATE TABLE IF NOT EXISTS ACCOUNT_LEASE
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 LESSOR_ID BIGINT NOT NULL,
 CURRENT_LEASING_HEIGHT_FROM INTEGER,
 CURRENT_LEASING_HEIGHT_TO INTEGER,
 CURRENT_LESSEE_ID BIGINT,
 NEXT_LEASING_HEIGHT_FROM INTEGER,
 NEXT_LEASING_HEIGHT_TO INTEGER,
 NEXT_LESSEE_ID BIGINT,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX ACCOUNT_LEASE_LESSOR_ID_HEIGHT_IDX ON ACCOUNT_LEASE (LESSOR_ID, HEIGHT DESC);
CREATE INDEX ACCOUNT_LEASE_CURRENT_LEASING_HEIGHT_FROM_IDX ON ACCOUNT_LEASE (CURRENT_LEASING_HEIGHT_FROM);
CREATE INDEX ACCOUNT_LEASE_CURRENT_LEASING_HEIGHT_TO_IDX ON ACCOUNT_LEASE (CURRENT_LEASING_HEIGHT_TO);
CREATE INDEX ACCOUNT_LEASE_HEIGHT_ID_IDX ON ACCOUNT_LEASE (HEIGHT, LESSOR_ID);
CREATE TABLE IF NOT EXISTS ACCOUNT_LEDGER
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 EVENT_TYPE SMALLINT NOT NULL,
 EVENT_ID BIGINT NOT NULL,
 HOLDING_TYPE SMALLINT NOT NULL,
 HOLDING_ID BIGINT,
 "CHANGE" BIGINT NOT NULL,
 BALANCE BIGINT NOT NULL,
 BLOCK_ID BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL,
 TIMESTAMP INTEGER NOT NULL
);
CREATE INDEX ACCOUNT_LEDGER_ID_IDX ON ACCOUNT_LEDGER (ACCOUNT_ID, DB_ID);
CREATE INDEX ACCOUNT_LEDGER_HEIGHT_IDX ON ACCOUNT_LEDGER (HEIGHT);
CREATE TABLE IF NOT EXISTS ACCOUNT_PROPERTY
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 RECIPIENT_ID BIGINT NOT NULL,
 SETTER_ID BIGINT,
 PROPERTY varchar(5000) NOT NULL,
 VALUE varchar(5000),
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX ACCOUNT_PROPERTY_ID_HEIGHT_IDX ON ACCOUNT_PROPERTY (ID, HEIGHT DESC);
CREATE INDEX ACCOUNT_PROPERTY_RECIPIENT_HEIGHT_IDX ON ACCOUNT_PROPERTY (RECIPIENT_ID, HEIGHT DESC);
CREATE INDEX ACCOUNT_PROPERTY_SETTER_RECIPIENT_IDX ON ACCOUNT_PROPERTY (SETTER_ID, RECIPIENT_ID);
CREATE INDEX ACCOUNT_PROPERTY_HEIGHT_ID_IDX ON ACCOUNT_PROPERTY (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS ALIAS
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 ALIAS_NAME varchar(320) NOT NULL,
 ALIAS_NAME_LOWER varchar(320) NOT NULL,
 ALIAS_URI varchar(5000) NOT NULL,
 TIMESTAMP INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX ALIAS_ID_HEIGHT_IDX ON ALIAS (ID, HEIGHT DESC);
CREATE INDEX ALIAS_ACCOUNT_ID_IDX ON ALIAS (ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX ALIAS_NAME_LOWER_IDX ON ALIAS (ALIAS_NAME_LOWER);
CREATE INDEX ALIAS_HEIGHT_ID_IDX ON ALIAS (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS ALIAS_OFFER
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 PRICE BIGINT NOT NULL,
 BUYER_ID BIGINT,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX ALIAS_OFFER_ID_HEIGHT_IDX ON ALIAS_OFFER (ID, HEIGHT DESC);
CREATE INDEX ALIAS_OFFER_HEIGHT_ID_IDX ON ALIAS_OFFER (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS ASK_ORDER
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 ASSET_ID BIGINT NOT NULL,
 PRICE BIGINT NOT NULL,
 TRANSACTION_INDEX SMALLINT NOT NULL,
 TRANSACTION_HEIGHT INTEGER NOT NULL,
 QUANTITY BIGINT NOT NULL,
 CREATION_HEIGHT INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX ASK_ORDER_ID_HEIGHT_IDX ON ASK_ORDER (ID, HEIGHT DESC);
CREATE INDEX ASK_ORDER_ACCOUNT_ID_IDX ON ASK_ORDER (ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX ASK_ORDER_ASSET_ID_PRICE_IDX ON ASK_ORDER (ASSET_ID, PRICE);
CREATE INDEX ASK_ORDER_CREATION_IDX ON ASK_ORDER (CREATION_HEIGHT DESC);
CREATE INDEX ASK_ORDER_HEIGHT_ID_IDX ON ASK_ORDER (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS ASSET
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 NAME varchar(5000) NOT NULL,
 DESCRIPTION varchar(5000),
 QUANTITY BIGINT NOT NULL,
 DECIMALS SMALLINT NOT NULL,
 HAS_CONTROL_PHASING BOOLEAN DEFAULT FALSE NOT NULL,
 INITIAL_QUANTITY BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX ASSET_ID_HEIGHT_IDX ON ASSET (ID, HEIGHT DESC);
CREATE INDEX ASSET_ACCOUNT_ID_IDX ON ASSET (ACCOUNT_ID);
CREATE INDEX ASSET_HEIGHT_ID_IDX ON ASSET (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS ASSET_DELETE
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 ASSET_ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 QUANTITY BIGINT NOT NULL,
 TIMESTAMP INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL
);
CREATE UNIQUE INDEX ASSET_DELETE_ID_IDX ON ASSET_DELETE (ID);
CREATE INDEX ASSET_DELETE_ASSET_ID_IDX ON ASSET_DELETE (ASSET_ID, HEIGHT DESC);
CREATE INDEX ASSET_DELETE_ACCOUNT_ID_IDX ON ASSET_DELETE (ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX ASSET_DELETE_HEIGHT_IDX ON ASSET_DELETE (HEIGHT);
CREATE TABLE IF NOT EXISTS ASSET_DIVIDEND
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 ASSET_ID BIGINT NOT NULL,
 AMOUNT BIGINT NOT NULL,
 DIVIDEND_HEIGHT INTEGER NOT NULL,
 TOTAL_DIVIDEND BIGINT NOT NULL,
 NUM_ACCOUNTS BIGINT NOT NULL,
 TIMESTAMP INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL
);
CREATE UNIQUE INDEX ASSET_DIVIDEND_ID_IDX ON ASSET_DIVIDEND (ID);
CREATE INDEX ASSET_DIVIDEND_ASSET_ID_IDX ON ASSET_DIVIDEND (ASSET_ID, HEIGHT DESC);
CREATE INDEX ASSET_DIVIDEND_HEIGHT_IDX ON ASSET_DIVIDEND (HEIGHT);
CREATE TABLE IF NOT EXISTS ASSET_TRANSFER
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 ASSET_ID BIGINT NOT NULL,
 SENDER_ID BIGINT NOT NULL,
 RECIPIENT_ID BIGINT NOT NULL,
 QUANTITY BIGINT NOT NULL,
 TIMESTAMP INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL
);
CREATE UNIQUE INDEX ASSET_TRANSFER_ID_IDX ON ASSET_TRANSFER (ID);
CREATE INDEX ASSET_TRANSFER_ASSET_ID_IDX ON ASSET_TRANSFER (ASSET_ID, HEIGHT DESC);
CREATE INDEX ASSET_TRANSFER_SENDER_ID_IDX ON ASSET_TRANSFER (SENDER_ID, HEIGHT DESC);
CREATE INDEX ASSET_TRANSFER_RECIPIENT_ID_IDX ON ASSET_TRANSFER (RECIPIENT_ID, HEIGHT DESC);
CREATE INDEX ASSET_TRANSFER_HEIGHT_IDX ON ASSET_TRANSFER (HEIGHT);
CREATE TABLE IF NOT EXISTS BID_ORDER
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 ASSET_ID BIGINT NOT NULL,
 PRICE BIGINT NOT NULL,
 TRANSACTION_INDEX SMALLINT NOT NULL,
 TRANSACTION_HEIGHT INTEGER NOT NULL,
 QUANTITY BIGINT NOT NULL,
 CREATION_HEIGHT INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX BID_ORDER_ID_HEIGHT_IDX ON BID_ORDER (ID, HEIGHT DESC);
CREATE INDEX BID_ORDER_ACCOUNT_ID_IDX ON BID_ORDER (ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX BID_ORDER_ASSET_ID_PRICE_IDX ON BID_ORDER (ASSET_ID, PRICE DESC);
CREATE INDEX BID_ORDER_CREATION_IDX ON BID_ORDER (CREATION_HEIGHT DESC);
CREATE INDEX BID_ORDER_HEIGHT_ID_IDX ON BID_ORDER (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS BLOCK
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 VERSION INTEGER NOT NULL,
 TIMESTAMP INTEGER NOT NULL,
 PREVIOUS_BLOCK_ID BIGINT,
 TOTAL_AMOUNT BIGINT NOT NULL,
 TOTAL_FEE BIGINT NOT NULL,
 PAYLOAD_LENGTH INTEGER NOT NULL,
 PREVIOUS_BLOCK_HASH BYTEA,
 CUMULATIVE_DIFFICULTY BYTEA NOT NULL,
 BASE_TARGET BIGINT NOT NULL,
 NEXT_BLOCK_ID BIGINT,
 HEIGHT INTEGER NOT NULL,
 GENERATION_SIGNATURE BYTEA NOT NULL,
 BLOCK_SIGNATURE BYTEA NOT NULL,
 PAYLOAD_HASH BYTEA NOT NULL,
 GENERATOR_ID BIGINT NOT NULL
);
CREATE UNIQUE INDEX BLOCK_ID_IDX ON BLOCK (ID);
CREATE UNIQUE INDEX BLOCK_TIMESTAMP_IDX ON BLOCK (TIMESTAMP DESC);
CREATE UNIQUE INDEX BLOCK_HEIGHT_IDX ON BLOCK (HEIGHT);
CREATE INDEX BLOCK_GENERATOR_ID_IDX ON BLOCK (GENERATOR_ID);
CREATE TABLE IF NOT EXISTS BUY_OFFER
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 CURRENCY_ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 RATE BIGINT NOT NULL,
 UNIT_LIMIT BIGINT NOT NULL,
 SUPPLY BIGINT NOT NULL,
 EXPIRATION_HEIGHT INTEGER NOT NULL,
 TRANSACTION_HEIGHT INTEGER NOT NULL,
 CREATION_HEIGHT INTEGER NOT NULL,
 TRANSACTION_INDEX SMALLINT NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX BUY_OFFER_ID_IDX ON BUY_OFFER (ID, HEIGHT DESC);
CREATE INDEX BUY_OFFER_CURRENCY_ID_ACCOUNT_ID_IDX ON BUY_OFFER (CURRENCY_ID, ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX BUY_OFFER_RATE_HEIGHT_IDX ON BUY_OFFER (RATE DESC, CREATION_HEIGHT);
CREATE INDEX BUY_OFFER_HEIGHT_ID_IDX ON BUY_OFFER (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS CURRENCY
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 NAME varchar(320) NOT NULL,
 NAME_LOWER varchar(320) NOT NULL,
 CODE varchar(320) NOT NULL,
 DESCRIPTION varchar(5000),
 TYPE INTEGER NOT NULL,
 INITIAL_SUPPLY BIGINT DEFAULT 0 NOT NULL,
 RESERVE_SUPPLY BIGINT NOT NULL,
 MAX_SUPPLY BIGINT NOT NULL,
 CREATION_HEIGHT INTEGER NOT NULL,
 ISSUANCE_HEIGHT INTEGER NOT NULL,
 MIN_RESERVE_PER_UNIT_NQT BIGINT NOT NULL,
 MIN_DIFFICULTY SMALLINT NOT NULL,
 MAX_DIFFICULTY SMALLINT NOT NULL,
 RULESET SMALLINT NOT NULL,
 ALGORITHM SMALLINT NOT NULL,
 DECIMALS SMALLINT DEFAULT 0 NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX CURRENCY_ID_HEIGHT_IDX ON CURRENCY (ID, HEIGHT DESC);
CREATE INDEX CURRENCY_ACCOUNT_ID_IDX ON CURRENCY (ACCOUNT_ID);
CREATE INDEX CURRENCY_NAME_IDX ON CURRENCY (NAME_LOWER, HEIGHT DESC);
CREATE INDEX CURRENCY_CODE_IDX ON CURRENCY (CODE, HEIGHT DESC);
CREATE INDEX CURRENCY_CREATION_HEIGHT_IDX ON CURRENCY (CREATION_HEIGHT DESC);
CREATE INDEX CURRENCY_ISSUANCE_HEIGHT_IDX ON CURRENCY (ISSUANCE_HEIGHT);
CREATE INDEX CURRENCY_HEIGHT_ID_IDX ON CURRENCY (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS CURRENCY_FOUNDER
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 CURRENCY_ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 AMOUNT BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX CURRENCY_FOUNDER_CURRENCY_ID_IDX ON CURRENCY_FOUNDER (CURRENCY_ID, ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX CURRENCY_FOUNDER_ACCOUNT_ID_IDX ON CURRENCY_FOUNDER (ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX CURRENCY_FOUNDER_HEIGHT_ID_IDX ON CURRENCY_FOUNDER (HEIGHT, CURRENCY_ID, ACCOUNT_ID);
CREATE TABLE IF NOT EXISTS CURRENCY_MINT
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 CURRENCY_ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 COUNTER BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX CURRENCY_MINT_CURRENCY_ID_ACCOUNT_ID_IDX ON CURRENCY_MINT (CURRENCY_ID, ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX CURRENCY_MINT_HEIGHT_ID_IDX ON CURRENCY_MINT (HEIGHT, CURRENCY_ID, ACCOUNT_ID);
CREATE TABLE IF NOT EXISTS CURRENCY_SUPPLY
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 CURRENT_SUPPLY BIGINT NOT NULL,
 CURRENT_RESERVE_PER_UNIT_NQT BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX CURRENCY_SUPPLY_ID_HEIGHT_IDX ON CURRENCY_SUPPLY (ID, HEIGHT DESC);
CREATE INDEX CURRENCY_SUPPLY_HEIGHT_ID_IDX ON CURRENCY_SUPPLY (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS CURRENCY_TRANSFER
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 CURRENCY_ID BIGINT NOT NULL,
 SENDER_ID BIGINT NOT NULL,
 RECIPIENT_ID BIGINT NOT NULL,
 UNITS BIGINT NOT NULL,
 TIMESTAMP INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL
);
CREATE UNIQUE INDEX CURRENCY_TRANSFER_ID_IDX ON CURRENCY_TRANSFER (ID);
CREATE INDEX CURRENCY_TRANSFER_CURRENCY_ID_IDX ON CURRENCY_TRANSFER (CURRENCY_ID, HEIGHT DESC);
CREATE INDEX CURRENCY_TRANSFER_SENDER_ID_IDX ON CURRENCY_TRANSFER (SENDER_ID, HEIGHT DESC);
CREATE INDEX CURRENCY_TRANSFER_RECIPIENT_ID_IDX ON CURRENCY_TRANSFER (RECIPIENT_ID, HEIGHT DESC);
CREATE INDEX CURRENCY_TRANSFER_HEIGHT_IDX ON CURRENCY_TRANSFER (HEIGHT);
CREATE TABLE IF NOT EXISTS DATA_TAG
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 TAG varchar(300) NOT NULL,
 TAG_COUNT INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL,
 CONSTRAINT CONSTRAINT_995 FOREIGN KEY (HEIGHT) REFERENCES BLOCK (HEIGHT) ON DELETE CASCADE
);
CREATE UNIQUE INDEX DATA_TAG_TAG_HEIGHT_IDX ON DATA_TAG (TAG, HEIGHT DESC);
CREATE INDEX DATA_TAG_COUNT_HEIGHT_IDX ON DATA_TAG (TAG_COUNT DESC, HEIGHT DESC);

CREATE TABLE IF NOT EXISTS EXCHANGE
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 TRANSACTION_ID BIGINT NOT NULL,
 CURRENCY_ID BIGINT NOT NULL,
 BLOCK_ID BIGINT NOT NULL,
 OFFER_ID BIGINT NOT NULL,
 SELLER_ID BIGINT NOT NULL,
 BUYER_ID BIGINT NOT NULL,
 UNITS BIGINT NOT NULL,
 RATE BIGINT NOT NULL,
 TIMESTAMP INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL
);
CREATE UNIQUE INDEX EXCHANGE_OFFER_IDX ON EXCHANGE (TRANSACTION_ID, OFFER_ID);
CREATE INDEX EXCHANGE_CURRENCY_ID_IDX ON EXCHANGE (CURRENCY_ID, HEIGHT DESC);
CREATE INDEX EXCHANGE_SELLER_ID_IDX ON EXCHANGE (SELLER_ID, HEIGHT DESC);
CREATE INDEX EXCHANGE_BUYER_ID_IDX ON EXCHANGE (BUYER_ID, HEIGHT DESC);
CREATE INDEX EXCHANGE_HEIGHT_DB_ID_IDX ON EXCHANGE (HEIGHT DESC, DB_ID DESC);
CREATE INDEX EXCHANGE_HEIGHT_IDX ON EXCHANGE (HEIGHT);
CREATE TABLE IF NOT EXISTS EXCHANGE_REQUEST
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 CURRENCY_ID BIGINT NOT NULL,
 UNITS BIGINT NOT NULL,
 RATE BIGINT NOT NULL,
 IS_BUY BOOLEAN NOT NULL,
 TIMESTAMP INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL
);
CREATE UNIQUE INDEX EXCHANGE_REQUEST_ID_IDX ON EXCHANGE_REQUEST (ID);
CREATE INDEX EXCHANGE_REQUEST_ACCOUNT_CURRENCY_IDX ON EXCHANGE_REQUEST (ACCOUNT_ID, CURRENCY_ID, HEIGHT DESC);
CREATE INDEX EXCHANGE_REQUEST_CURRENCY_IDX ON EXCHANGE_REQUEST (CURRENCY_ID, HEIGHT DESC);
CREATE INDEX EXCHANGE_REQUEST_HEIGHT_DB_ID_IDX ON EXCHANGE_REQUEST (HEIGHT DESC, DB_ID DESC);
CREATE INDEX EXCHANGE_REQUEST_HEIGHT_IDX ON EXCHANGE_REQUEST (HEIGHT);
CREATE TABLE IF NOT EXISTS GOODS
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 SELLER_ID BIGINT NOT NULL,
 NAME varchar(300) NOT NULL,
 DESCRIPTION varchar(5000),
 PARSED_TAGS varchar(5000),
 TAGS varchar(2000),
 TIMESTAMP INTEGER NOT NULL,
 QUANTITY INTEGER NOT NULL,
 PRICE BIGINT NOT NULL,
 DELISTED BOOLEAN NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL,
 HAS_IMAGE BOOLEAN DEFAULT FALSE NOT NULL
);
CREATE UNIQUE INDEX GOODS_ID_HEIGHT_IDX ON GOODS (ID, HEIGHT DESC);
CREATE INDEX GOODS_SELLER_ID_NAME_IDX ON GOODS (SELLER_ID, NAME);
CREATE INDEX GOODS_TIMESTAMP_IDX ON GOODS (TIMESTAMP DESC, HEIGHT DESC);
CREATE INDEX GOODS_HEIGHT_ID_IDX ON GOODS (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS HUB
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ACCOUNT_ID BIGINT,
 MIN_FEE_PER_BYTE BIGINT,
 URIS varchar(5000),
 HEIGHT INTEGER,
 LATEST BOOLEAN
);

CREATE TABLE IF NOT EXISTS PEER
(
 ADDRESS varchar(220) PRIMARY KEY NOT NULL,
 LAST_UPDATED INTEGER,
 SERVICES BIGINT
);

CREATE TABLE IF NOT EXISTS PHASING_POLL
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 WHITELIST_SIZE SMALLINT DEFAULT 0 NOT NULL,
 FINISH_HEIGHT INTEGER NOT NULL,
 VOTING_MODEL SMALLINT NOT NULL,
 QUORUM BIGINT,
 MIN_BALANCE BIGINT,
 HOLDING_ID BIGINT,
 MIN_BALANCE_MODEL SMALLINT,
 HASHED_SECRET BYTEA,
 ALGORITHM SMALLINT,
 HEIGHT INTEGER NOT NULL
);
CREATE UNIQUE INDEX PHASING_POLL_ID_IDX ON PHASING_POLL (ID);
CREATE INDEX PHASING_POLL_ACCOUNT_ID_IDX ON PHASING_POLL (ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX PHASING_POLL_HOLDING_ID_IDX ON PHASING_POLL (HOLDING_ID, HEIGHT DESC);
CREATE INDEX PHASING_POLL_HEIGHT_IDX ON PHASING_POLL (HEIGHT);
CREATE TABLE IF NOT EXISTS PHASING_POLL_LINKED_TRANSACTION
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 TRANSACTION_ID BIGINT NOT NULL,
 LINKED_FULL_HASH BYTEA NOT NULL,
 LINKED_TRANSACTION_ID BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL
);
CREATE UNIQUE INDEX PHASING_POLL_LINKED_TRANSACTION_ID_LINK_IDX ON PHASING_POLL_LINKED_TRANSACTION (TRANSACTION_ID, LINKED_TRANSACTION_ID);
CREATE UNIQUE INDEX PHASING_POLL_LINKED_TRANSACTION_LINK_ID_IDX ON PHASING_POLL_LINKED_TRANSACTION (LINKED_TRANSACTION_ID, TRANSACTION_ID);
CREATE INDEX PHASING_POLL_LINKED_TRANSACTION_HEIGHT_IDX ON PHASING_POLL_LINKED_TRANSACTION (HEIGHT);
CREATE TABLE IF NOT EXISTS PHASING_POLL_RESULT
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 RESULT BIGINT NOT NULL,
 APPROVED BOOLEAN NOT NULL,
 HEIGHT INTEGER NOT NULL
);
CREATE UNIQUE INDEX PHASING_POLL_RESULT_ID_IDX ON PHASING_POLL_RESULT (ID);
CREATE INDEX PHASING_POLL_RESULT_HEIGHT_IDX ON PHASING_POLL_RESULT (HEIGHT);
CREATE TABLE IF NOT EXISTS PHASING_POLL_VOTER
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 TRANSACTION_ID BIGINT NOT NULL,
 VOTER_ID BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL
);
CREATE UNIQUE INDEX PHASING_POLL_VOTER_TRANSACTION_VOTER_IDX ON PHASING_POLL_VOTER (TRANSACTION_ID, VOTER_ID);
CREATE INDEX PHASING_POLL_VOTER_HEIGHT_IDX ON PHASING_POLL_VOTER (HEIGHT);
CREATE TABLE IF NOT EXISTS PHASING_VOTE
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 VOTE_ID BIGINT NOT NULL,
 TRANSACTION_ID BIGINT NOT NULL,
 VOTER_ID BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL
);
CREATE UNIQUE INDEX PHASING_VOTE_TRANSACTION_VOTER_IDX ON PHASING_VOTE (TRANSACTION_ID, VOTER_ID);
CREATE INDEX PHASING_VOTE_HEIGHT_IDX ON PHASING_VOTE (HEIGHT);
CREATE TABLE IF NOT EXISTS POLL
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 NAME varchar(5000) NOT NULL,
 DESCRIPTION varchar(5000),
 OPTIONS varchar(5000) NOT NULL,
 MIN_NUM_OPTIONS SMALLINT,
 MAX_NUM_OPTIONS SMALLINT,
 MIN_RANGE_VALUE SMALLINT,
 MAX_RANGE_VALUE SMALLINT,
 TIMESTAMP INTEGER NOT NULL,
 FINISH_HEIGHT INTEGER NOT NULL,
 VOTING_MODEL SMALLINT NOT NULL,
 MIN_BALANCE BIGINT,
 MIN_BALANCE_MODEL SMALLINT,
 HOLDING_ID BIGINT,
 HEIGHT INTEGER NOT NULL
);
CREATE UNIQUE INDEX POLL_ID_IDX ON POLL (ID);
CREATE INDEX POLL_ACCOUNT_IDX ON POLL (ACCOUNT_ID);
CREATE INDEX POLL_FINISH_HEIGHT_IDX ON POLL (FINISH_HEIGHT DESC);
CREATE INDEX POLL_HEIGHT_IDX ON POLL (HEIGHT);
CREATE TABLE IF NOT EXISTS POLL_RESULT
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 POLL_ID BIGINT NOT NULL,
 RESULT BIGINT,
 WEIGHT BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL
);
CREATE INDEX POLL_RESULT_POLL_ID_IDX ON POLL_RESULT (POLL_ID);
CREATE INDEX POLL_RESULT_HEIGHT_IDX ON POLL_RESULT (HEIGHT);
CREATE TABLE IF NOT EXISTS PRUNABLE_MESSAGE
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 SENDER_ID BIGINT NOT NULL,
 RECIPIENT_ID BIGINT,
 MESSAGE BYTEA,
 MESSAGE_IS_TEXT BOOLEAN NOT NULL,
 IS_COMPRESSED BOOLEAN NOT NULL,
 ENCRYPTED_MESSAGE BYTEA,
 ENCRYPTED_IS_TEXT BOOLEAN DEFAULT FALSE,
 BLOCK_TIMESTAMP INTEGER NOT NULL,
 TRANSACTION_TIMESTAMP INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL,
 CONSTRAINT CONSTRAINT_B40 FOREIGN KEY (HEIGHT) REFERENCES BLOCK (HEIGHT) ON DELETE CASCADE
);
CREATE UNIQUE INDEX PRUNABLE_MESSAGE_ID_IDX ON PRUNABLE_MESSAGE (ID);
CREATE INDEX PRUNABLE_MESSAGE_SENDER_IDX ON PRUNABLE_MESSAGE (SENDER_ID);
CREATE INDEX PRUNABLE_MESSAGE_RECIPIENT_IDX ON PRUNABLE_MESSAGE (RECIPIENT_ID);
CREATE INDEX PRUNABLE_MESSAGE_BLOCK_TIMESTAMP_DBID_IDX ON PRUNABLE_MESSAGE (BLOCK_TIMESTAMP DESC, DB_ID DESC);
CREATE INDEX PRUNABLE_MESSAGE_TRANSACTION_TIMESTAMP_IDX ON PRUNABLE_MESSAGE (TRANSACTION_TIMESTAMP DESC);
CREATE TABLE IF NOT EXISTS PUBLIC_KEY
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 PUBLIC_KEY BYTEA,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL,
 CONSTRAINT CONSTRAINT_8E8 FOREIGN KEY (HEIGHT) REFERENCES BLOCK (HEIGHT) ON DELETE CASCADE
);
CREATE UNIQUE INDEX PUBLIC_KEY_ACCOUNT_ID_HEIGHT_IDX ON PUBLIC_KEY (ACCOUNT_ID, HEIGHT DESC);
CREATE TABLE IF NOT EXISTS PURCHASE
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 BUYER_ID BIGINT NOT NULL,
 GOODS_ID BIGINT NOT NULL,
 SELLER_ID BIGINT NOT NULL,
 QUANTITY INTEGER NOT NULL,
 PRICE BIGINT NOT NULL,
 DEADLINE INTEGER NOT NULL,
 NOTE BYTEA,
 NONCE BYTEA,
 TIMESTAMP INTEGER NOT NULL,
 PENDING BOOLEAN NOT NULL,
 GOODS BYTEA,
 GOODS_NONCE BYTEA,
 GOODS_IS_TEXT BOOLEAN DEFAULT TRUE NOT NULL,
 REFUND_NOTE BYTEA,
 REFUND_NONCE BYTEA,
 HAS_FEEDBACK_NOTES BOOLEAN DEFAULT FALSE NOT NULL,
 HAS_PUBLIC_FEEDBACKS BOOLEAN DEFAULT FALSE NOT NULL,
 DISCOUNT BIGINT NOT NULL,
 REFUND BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX PURCHASE_ID_HEIGHT_IDX ON PURCHASE (ID, HEIGHT DESC);
CREATE INDEX PURCHASE_BUYER_ID_HEIGHT_IDX ON PURCHASE (BUYER_ID, HEIGHT DESC);
CREATE INDEX PURCHASE_SELLER_ID_HEIGHT_IDX ON PURCHASE (SELLER_ID, HEIGHT DESC);
CREATE INDEX PURCHASE_DEADLINE_IDX ON PURCHASE (DEADLINE DESC, HEIGHT DESC);
CREATE INDEX PURCHASE_TIMESTAMP_IDX ON PURCHASE (TIMESTAMP DESC, ID);
CREATE INDEX PURCHASE_HEIGHT_ID_IDX ON PURCHASE (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS PURCHASE_FEEDBACK
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 FEEDBACK_DATA BYTEA NOT NULL,
 FEEDBACK_NONCE BYTEA NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE INDEX PURCHASE_FEEDBACK_ID_HEIGHT_IDX ON PURCHASE_FEEDBACK (ID, HEIGHT DESC);
CREATE INDEX PURCHASE_FEEDBACK_HEIGHT_ID_IDX ON PURCHASE_FEEDBACK (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS PURCHASE_PUBLIC_FEEDBACK
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 PUBLIC_FEEDBACK varchar(5000) NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE INDEX PURCHASE_PUBLIC_FEEDBACK_ID_HEIGHT_IDX ON PURCHASE_PUBLIC_FEEDBACK (ID, HEIGHT DESC);
CREATE INDEX PURCHASE_PUBLIC_FEEDBACK_HEIGHT_ID_IDX ON PURCHASE_PUBLIC_FEEDBACK (HEIGHT, ID);

CREATE TABLE IF NOT EXISTS SCAN
(
 RESCAN BOOLEAN DEFAULT FALSE NOT NULL,
 HEIGHT INTEGER DEFAULT 0 NOT NULL,
 VALIDATE BOOLEAN DEFAULT FALSE NOT NULL
);
INSERT INTO SCAN (rescan, height, validate) VALUES (false, 0, false);
CREATE TABLE IF NOT EXISTS SELL_OFFER
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 CURRENCY_ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 RATE BIGINT NOT NULL,
 UNIT_LIMIT BIGINT NOT NULL,
 SUPPLY BIGINT NOT NULL,
 EXPIRATION_HEIGHT INTEGER NOT NULL,
 TRANSACTION_HEIGHT INTEGER NOT NULL,
 CREATION_HEIGHT INTEGER NOT NULL,
 TRANSACTION_INDEX SMALLINT NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX SELL_OFFER_ID_IDX ON SELL_OFFER (ID, HEIGHT DESC);
CREATE INDEX SELL_OFFER_CURRENCY_ID_ACCOUNT_ID_IDX ON SELL_OFFER (CURRENCY_ID, ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX SELL_OFFER_RATE_HEIGHT_IDX ON SELL_OFFER (RATE, CREATION_HEIGHT);
CREATE INDEX SELL_OFFER_HEIGHT_ID_IDX ON SELL_OFFER (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS SHUFFLING
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 HOLDING_ID BIGINT,
 HOLDING_TYPE SMALLINT NOT NULL,
 ISSUER_ID BIGINT NOT NULL,
 AMOUNT BIGINT NOT NULL,
 PARTICIPANT_COUNT SMALLINT NOT NULL,
 BLOCKS_REMAINING SMALLINT,
 STAGE SMALLINT NOT NULL,
 ASSIGNEE_ACCOUNT_ID BIGINT,
 REGISTRANT_COUNT SMALLINT NOT NULL,
 RECIPIENT_PUBLIC_KEYS varchar(5000),
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX SHUFFLING_ID_HEIGHT_IDX ON SHUFFLING (ID, HEIGHT DESC);
CREATE INDEX SHUFFLING_HOLDING_ID_HEIGHT_IDX ON SHUFFLING (HOLDING_ID, HEIGHT DESC);
CREATE INDEX SHUFFLING_BLOCKS_REMAINING_HEIGHT_IDX ON SHUFFLING (BLOCKS_REMAINING, HEIGHT DESC);
CREATE INDEX SHUFFLING_ASSIGNEE_ACCOUNT_ID_HEIGHT_IDX ON SHUFFLING (ASSIGNEE_ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX SHUFFLING_HEIGHT_ID_IDX ON SHUFFLING (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS SHUFFLING_DATA
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 SHUFFLING_ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 DATA varchar(5000),
 TRANSACTION_TIMESTAMP INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL,
 CONSTRAINT CONSTRAINT_A08 FOREIGN KEY (HEIGHT) REFERENCES BLOCK (HEIGHT) ON DELETE CASCADE
);
CREATE UNIQUE INDEX SHUFFLING_DATA_ID_HEIGHT_IDX ON SHUFFLING_DATA (SHUFFLING_ID, HEIGHT DESC);
CREATE INDEX SHUFFLING_DATA_TRANSACTION_TIMESTAMP_IDX ON SHUFFLING_DATA (TRANSACTION_TIMESTAMP DESC);
CREATE TABLE IF NOT EXISTS SHUFFLING_PARTICIPANT
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 SHUFFLING_ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 NEXT_ACCOUNT_ID BIGINT,
 PARTICIPANT_INDEX SMALLINT NOT NULL,
 STATE SMALLINT NOT NULL,
 BLAME_DATA varchar(5000),
 KEY_SEEDS varchar(5000),
 DATA_TRANSACTION_FULL_HASH BYTEA,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX SHUFFLING_PARTICIPANT_SHUFFLING_ID_ACCOUNT_ID_IDX ON SHUFFLING_PARTICIPANT (SHUFFLING_ID, ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX SHUFFLING_PARTICIPANT_HEIGHT_IDX ON SHUFFLING_PARTICIPANT (HEIGHT, SHUFFLING_ID, ACCOUNT_ID);
CREATE TABLE IF NOT EXISTS TAG
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 TAG varchar(320) NOT NULL,
 IN_STOCK_COUNT INTEGER NOT NULL,
 TOTAL_COUNT INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX TAG_TAG_IDX ON TAG (TAG, HEIGHT DESC);
CREATE INDEX TAG_IN_STOCK_COUNT_IDX ON TAG (IN_STOCK_COUNT DESC, HEIGHT DESC);
CREATE INDEX TAG_HEIGHT_TAG_IDX ON TAG (HEIGHT, TAG);
CREATE TABLE IF NOT EXISTS TAGGED_DATA
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 NAME varchar(2000) NOT NULL,
 DESCRIPTION varchar(5000),
 TAGS varchar(2000),
 PARSED_TAGS varchar(2000),
 TYPE varchar(2000),
 DATA BYTEA NOT NULL,
 IS_TEXT BOOLEAN NOT NULL,
 FILENAME varchar(2000),
 CHANNEL varchar(300),
 BLOCK_TIMESTAMP INTEGER NOT NULL,
 TRANSACTION_TIMESTAMP INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL,
 CONSTRAINT CONSTRAINT_8B9 FOREIGN KEY (HEIGHT) REFERENCES BLOCK (HEIGHT) ON DELETE CASCADE
);
CREATE UNIQUE INDEX TAGGED_DATA_ID_HEIGHT_IDX ON TAGGED_DATA (ID, HEIGHT DESC);
CREATE INDEX TAGGED_DATA_ACCOUNT_ID_HEIGHT_IDX ON TAGGED_DATA (ACCOUNT_ID, HEIGHT DESC);
CREATE INDEX TAGGED_DATA_CHANNEL_IDX ON TAGGED_DATA (CHANNEL, HEIGHT DESC);
CREATE INDEX TAGGED_DATA_BLOCK_TIMESTAMP_HEIGHT_DB_ID_IDX ON TAGGED_DATA (BLOCK_TIMESTAMP DESC, HEIGHT DESC, DB_ID DESC);
CREATE INDEX TAGGED_DATA_EXPIRATION_IDX ON TAGGED_DATA (TRANSACTION_TIMESTAMP DESC);
CREATE TABLE IF NOT EXISTS TAGGED_DATA_EXTEND
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 EXTEND_ID BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE INDEX TAGGED_DATA_EXTEND_ID_HEIGHT_IDX ON TAGGED_DATA_EXTEND (ID, HEIGHT DESC);
CREATE INDEX TAGGED_DATA_EXTEND_HEIGHT_ID_IDX ON TAGGED_DATA_EXTEND (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS TAGGED_DATA_TIMESTAMP
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 TIMESTAMP INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE UNIQUE INDEX TAGGED_DATA_TIMESTAMP_ID_HEIGHT_IDX ON TAGGED_DATA_TIMESTAMP (ID, HEIGHT DESC);
CREATE INDEX TAGGED_DATA_TIMESTAMP_HEIGHT_ID_IDX ON TAGGED_DATA_TIMESTAMP (HEIGHT, ID);
CREATE TABLE IF NOT EXISTS TRADE
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ASSET_ID BIGINT NOT NULL,
 BLOCK_ID BIGINT NOT NULL,
 ASK_ORDER_ID BIGINT NOT NULL,
 BID_ORDER_ID BIGINT NOT NULL,
 ASK_ORDER_HEIGHT INTEGER NOT NULL,
 BID_ORDER_HEIGHT INTEGER NOT NULL,
 SELLER_ID BIGINT NOT NULL,
 BUYER_ID BIGINT NOT NULL,
 IS_BUY BOOLEAN NOT NULL,
 QUANTITY BIGINT NOT NULL,
 PRICE BIGINT NOT NULL,
 TIMESTAMP INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL
);
CREATE INDEX TRADE_ASSET_ID_IDX ON TRADE (ASSET_ID, HEIGHT DESC);
CREATE INDEX TRADE_ASK_IDX ON TRADE (ASK_ORDER_ID, HEIGHT DESC);
CREATE INDEX TRADE_BID_IDX ON TRADE (BID_ORDER_ID, HEIGHT DESC);
CREATE INDEX TRADE_SELLER_ID_IDX ON TRADE (SELLER_ID, HEIGHT DESC);
CREATE INDEX TRADE_BUYER_ID_IDX ON TRADE (BUYER_ID, HEIGHT DESC);
CREATE INDEX TRADE_HEIGHT_DB_ID_IDX ON TRADE (HEIGHT DESC, DB_ID DESC);
CREATE INDEX TRADE_HEIGHT_IDX ON TRADE (HEIGHT);
CREATE TABLE IF NOT EXISTS TRANSACTION
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 DEADLINE SMALLINT NOT NULL,
 RECIPIENT_ID BIGINT,
 AMOUNT BIGINT NOT NULL,
 FEE BIGINT NOT NULL,
 FULL_HASH BYTEA NOT NULL,
 HEIGHT INTEGER NOT NULL,
 BLOCK_ID BIGINT NOT NULL,
 SIGNATURE BYTEA NOT NULL,
 TIMESTAMP INTEGER NOT NULL,
 TYPE SMALLINT NOT NULL,
 SUBTYPE SMALLINT NOT NULL,
 SENDER_ID BIGINT NOT NULL,
 BLOCK_TIMESTAMP INTEGER NOT NULL,
 REFERENCED_TRANSACTION_FULL_HASH BYTEA,
 TRANSACTION_INDEX SMALLINT NOT NULL,
 PHASED BOOLEAN DEFAULT FALSE NOT NULL,
 ATTACHMENT_BYTES BYTEA,
 VERSION SMALLINT NOT NULL,
 HAS_MESSAGE BOOLEAN DEFAULT FALSE NOT NULL,
 HAS_ENCRYPTED_MESSAGE BOOLEAN DEFAULT FALSE NOT NULL,
 HAS_PUBLIC_KEY_ANNOUNCEMENT BOOLEAN DEFAULT FALSE NOT NULL,
 HAS_PRUNABLE_MESSAGE BOOLEAN DEFAULT FALSE NOT NULL,
 HAS_PRUNABLE_ATTACHMENT BOOLEAN DEFAULT FALSE NOT NULL,
 EC_BLOCK_HEIGHT INTEGER DEFAULT NULL,
 EC_BLOCK_ID BIGINT DEFAULT NULL,
 HAS_ENCRYPTTOSELF_MESSAGE BOOLEAN DEFAULT FALSE NOT NULL,
 HAS_PRUNABLE_ENCRYPTED_MESSAGE BOOLEAN DEFAULT FALSE NOT NULL,
 CONSTRAINT CONSTRAINT_FFF FOREIGN KEY (BLOCK_ID) REFERENCES BLOCK (ID) ON DELETE CASCADE
);
CREATE UNIQUE INDEX TRANSACTION_ID_IDX ON TRANSACTION (ID);
CREATE INDEX TRANSACTION_RECIPIENT_ID_IDX ON TRANSACTION (RECIPIENT_ID);
CREATE INDEX TRANSACTION_SENDER_ID_IDX ON TRANSACTION (SENDER_ID);
CREATE INDEX TRANSACTION_BLOCK_TIMESTAMP_IDX ON TRANSACTION (BLOCK_TIMESTAMP DESC);
CREATE TABLE IF NOT EXISTS UNCONFIRMED_TRANSACTION
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 EXPIRATION INTEGER NOT NULL,
 TRANSACTION_HEIGHT INTEGER NOT NULL,
 FEE_PER_BYTE BIGINT NOT NULL,
 ARRIVAL_TIMESTAMP BIGINT NOT NULL,
 TRANSACTION_BYTES BYTEA NOT NULL,
 HEIGHT INTEGER NOT NULL,
 PRUNABLE_JSON varchar(5000)
);
CREATE UNIQUE INDEX UNCONFIRMED_TRANSACTION_ID_IDX ON UNCONFIRMED_TRANSACTION (ID);
CREATE INDEX UNCONFIRMED_TRANSACTION_EXPIRATION_IDX ON UNCONFIRMED_TRANSACTION (EXPIRATION DESC);
CREATE INDEX UNCONFIRMED_TRANSACTION_HEIGHT_FEE_TIMESTAMP_IDX ON UNCONFIRMED_TRANSACTION (TRANSACTION_HEIGHT, FEE_PER_BYTE DESC, ARRIVAL_TIMESTAMP);

CREATE TABLE IF NOT EXISTS VOTE
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 POLL_ID BIGINT NOT NULL,
 VOTER_ID BIGINT NOT NULL,
 VOTE_BYTES BYTEA NOT NULL,
 HEIGHT INTEGER NOT NULL
);
CREATE UNIQUE INDEX VOTE_ID_IDX ON VOTE (ID);
CREATE UNIQUE INDEX VOTE_POLL_ID_IDX ON VOTE (POLL_ID, VOTER_ID);
CREATE INDEX VOTE_HEIGHT_IDX ON VOTE (HEIGHT);


CREATE TABLE IF NOT EXISTS REFERENCED_TRANSACTION
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 TRANSACTION_ID BIGINT NOT NULL,
 REFERENCED_TRANSACTION_ID BIGINT NOT NULL,
 CONSTRAINT CONSTRAINT_4B1 FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTION (ID) ON DELETE CASCADE
);
CREATE INDEX REFERENCED_TRANSACTION_REFERENCED_TRANSACTION_ID_IDX ON REFERENCED_TRANSACTION (REFERENCED_TRANSACTION_ID);


CREATE TABLE IF NOT EXISTS CONTRACT_REFERENCE
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 CONTRACT_NAME VARCHAR(5000) NOT NULL,
 CONTRACT_PARAMS VARCHAR(5000),
 CONTRACT_TRANSACTION_CHAIN_ID INTEGER NOT NULL,
 CONTRACT_TRANSACTION_FULL_HASH BYTEA,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE INDEX CONTRACT_REFERENCE_HEIGHT_ID_IDX
 ON CONTRACT_REFERENCE (HEIGHT ASC, ID ASC);

CREATE UNIQUE INDEX CONTRACT_REFERENCE_ID_HEIGHT_IDX
 ON CONTRACT_REFERENCE (ID ASC, HEIGHT DESC);

CREATE INDEX CONTRACT_REFERENCE_ACCOUNT_HEIGHT_IDX
 ON CONTRACT_REFERENCE (ACCOUNT_ID ASC, HEIGHT DESC);

CREATE TABLE IF NOT EXISTS COIN_ORDER_FXT
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 CHAIN_ID INTEGER NOT NULL,
 EXCHANGE_ID INTEGER NOT NULL,
 FULL_HASH BYTEA NOT NULL,
 AMOUNT BIGINT NOT NULL,
 QUANTITY BIGINT NOT NULL,
 BID_PRICE BIGINT NOT NULL,
 ASK_PRICE BIGINT NOT NULL,
 CREATION_HEIGHT INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL,
 TRANSACTION_HEIGHT INTEGER NOT NULL,
 TRANSACTION_INDEX SMALLINT NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE INDEX COIN_ORDER_FXT_ACCOUNT_IDX
 ON COIN_ORDER_FXT (ACCOUNT_ID ASC);

CREATE INDEX COIN_ORDER_FXT_CHAIN_IDX
 ON COIN_ORDER_FXT (CHAIN_ID ASC, EXCHANGE_ID ASC);

CREATE INDEX COIN_ORDER_FXT_EXCHANGE_IDX
 ON COIN_ORDER_FXT (EXCHANGE_ID ASC);

CREATE INDEX COIN_ORDER_FXT_ID_IDX
 ON COIN_ORDER_FXT (ID ASC, HEIGHT DESC);

CREATE TABLE IF NOT EXISTS COIN_TRADE_FXT
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 CHAIN_ID INTEGER NOT NULL,
 EXCHANGE_ID INTEGER NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 BLOCK_ID BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL,
 TIMESTAMP INTEGER NOT NULL,
 EXCHANGE_QUANTITY BIGINT NOT NULL,
 EXCHANGE_PRICE BIGINT NOT NULL,
 ORDER_ID BIGINT NOT NULL,
 ORDER_FULL_HASH BYTEA NOT NULL,
 MATCH_ID BIGINT NOT NULL,
 MATCH_FULL_HASH BYTEA NOT NULL
);

CREATE INDEX COIN_TRADE_FXT_EXCHANGE_IDX
 ON COIN_TRADE_FXT (EXCHANGE_ID ASC);

CREATE INDEX COIN_TRADE_FXT_CHAIN_IDX
 ON COIN_TRADE_FXT (CHAIN_ID ASC);

CREATE INDEX COIN_TRADE_FXT_ACCOUNT_IDX
 ON COIN_TRADE_FXT (ACCOUNT_ID ASC);

CREATE INDEX COIN_TRADE_FXT_ORDER_IDX
 ON COIN_TRADE_FXT (ORDER_ID ASC);

CREATE TABLE IF NOT EXISTS BALANCE
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 BALANCE BIGINT NOT NULL,
 UNCONFIRMED_BALANCE BIGINT NOT NULL,
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE UNIQUE INDEX BALANCE_FXT_ID_HEIGHT_IDX
 ON BALANCE (ACCOUNT_ID ASC, HEIGHT DESC);

CREATE INDEX BALANCE_FXT_HEIGHT_ID_IDX
 ON BALANCE (HEIGHT ASC, ACCOUNT_ID ASC);



CREATE TABLE IF NOT EXISTS ASSET_PROPERTY
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 ASSET_ID BIGINT NOT NULL,
 SETTER_ID BIGINT NOT NULL,
 PROPERTY VARCHAR(320) NOT NULL,
 VALUE VARCHAR(5000),
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);


CREATE INDEX ASSET_PROPERTY_ASSET_HEIGHT_IDX
 ON ASSET_PROPERTY (ASSET_ID ASC, HEIGHT DESC);

CREATE INDEX ASSET_PROPERTY_HEIGHT_ID_IDX
 ON ASSET_PROPERTY (HEIGHT ASC, ID ASC);

CREATE UNIQUE INDEX ASSET_PROPERTY_ID_HEIGHT_IDX
 ON ASSET_PROPERTY (ID ASC, HEIGHT DESC);

CREATE INDEX ASSET_PROPERTY_SETTER_PROPERTY_IDX
 ON ASSET_PROPERTY (SETTER_ID ASC, PROPERTY ASC);


CREATE TABLE IF NOT EXISTS ASSET_HISTORY
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ID BIGINT NOT NULL,
 FULL_HASH BYTEA NOT NULL,
 ASSET_ID BIGINT NOT NULL,
 ACCOUNT_ID BIGINT NOT NULL,
 QUANTITY BIGINT NOT NULL,
 TIMESTAMP INTEGER NOT NULL,
 CHAIN_ID INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL
);

CREATE INDEX ASSET_HISTORY_ACCOUNT_ID_IDX
 ON ASSET_HISTORY (ACCOUNT_ID ASC, HEIGHT DESC);

CREATE INDEX ASSET_HISTORY_ASSET_ID_IDX
 ON ASSET_HISTORY (ASSET_ID ASC, HEIGHT DESC);

CREATE INDEX ASSET_HISTORY_HEIGHT_IDX
 ON ASSET_HISTORY (HEIGHT ASC);

CREATE INDEX ASSET_HISTORY_ID_IDX
 ON ASSET_HISTORY (ID ASC);

CREATE TABLE IF NOT EXISTS ASSET_CONTROL_PHASING
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ASSET_ID BIGINT NOT NULL,
 VOTING_MODEL SMALLINT NOT NULL,
 QUORUM BIGINT,
 MIN_BALANCE BIGINT,
 HOLDING_ID BIGINT,
 MIN_BALANCE_MODEL SMALLINT,
 WHITELIST VARCHAR(5000),
 EXPRESSION TEXT,
 SENDER_PROPERTY_SETTER_ID BIGINT,
 SENDER_PROPERTY_NAME VARCHAR(1000),
 SENDER_PROPERTY_VALUE VARCHAR(1000),
 RECIPIENT_PROPERTY_SETTER_ID BIGINT,
 RECIPIENT_PROPERTY_NAME VARCHAR(1000),
 RECIPIENT_PROPERTY_VALUE VARCHAR(1000),
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);


CREATE INDEX ASSET_CONTROL_PHASING_ID_HEIGHT_IDX
 ON ASSET_CONTROL_PHASING (ASSET_ID ASC, HEIGHT DESC);

CREATE INDEX ASSET_CONTROL_PHASING_HEIGHT_ID_IDX
 ON ASSET_CONTROL_PHASING (HEIGHT ASC, ASSET_ID ASC);


CREATE TABLE IF NOT EXISTS ASSET_CONTROL_PHASING_SUB_POLL
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 ASSET_ID BIGINT NOT NULL,
 NAME VARCHAR(1000),
 VOTING_MODEL SMALLINT NOT NULL,
 QUORUM BIGINT,
 MIN_BALANCE BIGINT,
 HOLDING_ID BIGINT,
 MIN_BALANCE_MODEL SMALLINT,
 WHITELIST VARCHAR(5000),
 SENDER_PROPERTY_SETTER_ID BIGINT,
 SENDER_PROPERTY_NAME VARCHAR(1000),
 SENDER_PROPERTY_VALUE VARCHAR(1000),
 RECIPIENT_PROPERTY_SETTER_ID BIGINT,
 RECIPIENT_PROPERTY_NAME VARCHAR(1000),
 RECIPIENT_PROPERTY_VALUE VARCHAR(1000),
 HEIGHT INTEGER NOT NULL,
 LATEST BOOLEAN DEFAULT TRUE NOT NULL
);


CREATE INDEX ASSET_CONTROL_PHASING_SUB_POLL_ID_HEIGHT_IDX
 ON ASSET_CONTROL_PHASING_SUB_POLL (ASSET_ID ASC, HEIGHT DESC);

CREATE INDEX ASSET_CONTROL_PHASING_SUB_POLL_HEIGHT_ID_IDX
 ON ASSET_CONTROL_PHASING_SUB_POLL (HEIGHT ASC, ASSET_ID ASC);


CREATE TABLE IF NOT EXISTS PHASING_POLL_HASHED_SECRET
(
 DB_ID BIGSERIAL PRIMARY KEY NOT NULL,
 HASHED_SECRET BYTEA NOT NULL,
 HASHED_SECRET_ID BIGINT NOT NULL,
 ALGORITHM SMALLINT NOT NULL,
 TRANSACTION_FULL_HASH BYTEA,
 TRANSACTION_ID BIGINT NOT NULL,
 CHAIN_ID INTEGER NOT NULL,
 FINISH_HEIGHT INTEGER NOT NULL,
 HEIGHT INTEGER NOT NULL
);


CREATE INDEX PHASING_POLL_HASHED_SECRET_ID_IX
 ON PHASING_POLL_HASHED_SECRET (HASHED_SECRET_ID ASC);

CREATE INDEX PHASING_POLL_HASHED_SECRET_HEIGHT_IDX
 ON PHASING_POLL_HASHED_SECRET (HEIGHT ASC);

CREATE INDEX PHASING_POLL_HASHED_SECRET_TRANSACTION_ID_IDX
 ON PHASING_POLL_HASHED_SECRET (TRANSACTION_ID ASC);


/* 如果是历史库需要增加此字段
alter table asset add column HAS_CONTROL_PHASING BOOLEAN DEFAULT FALSE NOT NULL
*/
/*
grant all privileges on *.* to 'nrcs'@'localhost'
*/
