# Generate Rust ORM models from schema_analysis.json
# Version: 3 - fixed skipping

$SchemaPath = "D:/workspace/git/rust-nrcs/crates/orm/schema_analysis.json"
$OutputPath = "D:/workspace/git/rust-nrcs/crates/orm/src/generated_models.rs"

Write-Host "Reading schema..."
$schema = Get-Content $SchemaPath -Raw | ConvertFrom-Json

# Existing model full names (as they appear in code)
$existingFull = @('BlockModel','TransactionModel','AccountModel','AccountAssetModel','AssetModel','ContractModel','TransactionReceiptModel')

function To-RustTypeName($tableName) {
    $camel = ($tableName -split '_' | ForEach-Object {
        if ($_.Length -eq 0) { return '' }
        $first = $_.Substring(0,1).ToUpper()
        $rest = $_.Substring(1)
        $first + $rest
    }) -join ''
    return $camel + "Model"
}

function To-SnakeCase($name) {
    # H2 columns are typically UPPER_CASE. Just lowercase them to get snake_case.
    $lower = $name.ToLower()
    switch ($lower) {
        'type' { return 'type_' }
        'match' { return 'match_' }
        'in' { return 'in_' }
        default { return $lower }
    }
}

function Map-H2Type($dataType, $isNullable) {
    $base = switch -Wildcard ($dataType) {
        'binary*' { 'Vec<u8>' }
        'varbinary' { 'Vec<u8>' }
        'blob' { 'Vec<u8>' }
        'bigint' { 'i64' }
        'integer' { 'i32' }
        'smallint' { 'i16' }
        'tinyint' { 'i16' }
        'boolean' { 'bool' }
        'varchar*' { 'String' }
        'text' { 'String' }
        default { 'String' }
    }
    if ($isNullable -and $base -ne 'String' -and $base -ne 'Vec<u8>') {
        return "Option<$base>"
    }
    return $base
}

$sb = New-Object System.Text.StringBuilder

# Header
$null = $sb.AppendLine("//! Auto-generated ORM models. DO NOT EDIT MANUALLY.")
$null = $sb.AppendLine("//! Generated by tools/gen_models.ps1")
$null = $sb.AppendLine()
$null = $sb.AppendLine("use sqlx::FromRow;")
$null = $sb.AppendLine("use serde::{Deserialize, Serialize};")
$null = $sb.AppendLine("use chrono::{DateTime, Utc};")
$null = $sb.AppendLine("use crate::database::DbConnection;")
$null = $sb.AppendLine("use crate::error::BlockchainError;")
$null = $sb.AppendLine()

$generatedCount = 0
$tablesObject = $schema.tables
$tableEntries = $tablesObject.PSObject.Properties

foreach ($entry in $tableEntries) {
    $tblName = $entry.Name
    $table = $entry.Value
    $structName = To-RustTypeName $tblName

    if ($existingFull -contains $structName) {
        Write-Host "Skipping existing: $structName"
        continue
    }

    Write-Host "Generating: $tblName -> $structName"
    $generatedCount++

    # Struct
    $null = $sb.AppendLine("#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]")
    $null = $sb.AppendLine("pub struct " + $structName + " {")

    foreach ($col in $table.columns) {
        $fieldName = To-SnakeCase $col.name
        $rustType = Map-H2Type $col.data_type $col.is_nullable

        if ($col.name -ne $fieldName.ToUpper()) {
            $null = $sb.AppendLine('    #[sqlx(rename = "' + $col.name + '")]')
        }
        $null = $sb.AppendLine('    pub ' + $fieldName + ': ' + $rustType + ',')
    }

    $null = $sb.AppendLine("}")
    $null = $sb.AppendLine()

    # impl
    $null = $sb.AppendLine("impl " + $structName + " {")
    $null = $sb.AppendLine("    pub fn to_domain(&self) -> Result<Block, BlockchainError> {")
    $null = $sb.AppendLine("        unimplemented!()")
    $null = $sb.AppendLine("    }")
    $null = $sb.AppendLine()
    $null = $sb.AppendLine("    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {")
    $null = $sb.AppendLine("        unimplemented!()")
    $null = $sb.AppendLine("    }")
    $null = $sb.AppendLine("}")
    $null = $sb.AppendLine()

    # Repository trait
    $repoName = $structName -replace 'Model$','Repository'
    $null = $sb.AppendLine("#[async_trait]")
    $null = $sb.AppendLine("pub trait " + $repoName + ": Repository<" + $structName + "> {")
    $null = $sb.AppendLine("    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {")
    $null = $sb.AppendLine('        sqlx::query_as!(' + $structName + ', "SELECT * FROM ' + $table.name + ' WHERE db_id = ?", id)')
    $null = $sb.AppendLine("            .fetch_optional(conn)")
    $null = $sb.AppendLine("            .await")
    $null = $sb.AppendLine("    }")
    $null = $sb.AppendLine("}")
    $null = $sb.AppendLine()
}

[System.IO.File]::WriteAllText($OutputPath, $sb.ToString())
Write-Host "Generated $generatedCount models to $OutputPath"
