//! Auto-generated ORM models. DO NOT EDIT MANUALLY.
//! Generated by tools/gen_models.ps1

use sqlx::FromRow;
use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};
use crate::database::DbConnection;
use crate::error::BlockchainError;

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct PURCHASEFEEDBACKModel {
    pub db_id: i64,
    pub id: i64,
    pub feedback_data: Vec<u8>,
    pub feedback_nonce: Vec<u8>,
    pub height: i32,
    pub latest: bool,
}

impl PURCHASEFEEDBACKModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait PURCHASEFEEDBACKRepository: Repository<PURCHASEFEEDBACKModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(PURCHASEFEEDBACKModel, "SELECT * FROM PURCHASE_FEEDBACK WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct PHASINGPOLLLINKEDTRANSACTIONModel {
    pub db_id: i64,
    pub transaction_id: i64,
    pub linked_full_hash: Vec<u8>,
    pub linked_transaction_id: i64,
    pub height: i32,
}

impl PHASINGPOLLLINKEDTRANSACTIONModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait PHASINGPOLLLINKEDTRANSACTIONRepository: Repository<PHASINGPOLLLINKEDTRANSACTIONModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(PHASINGPOLLLINKEDTRANSACTIONModel, "SELECT * FROM PHASING_POLL_LINKED_TRANSACTION WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct SHUFFLINGModel {
    pub db_id: i64,
    pub id: i64,
    pub holding_id: Option<i64>,
    pub holding_type: i16,
    pub issuer_id: i64,
    pub amount: i64,
    pub participant_count: i16,
    pub blocks_remaining: Option<i16>,
    pub stage: i16,
    pub assignee_account_id: Option<i64>,
    pub registrant_count: i16,
    pub recipient_public_keys: String,
    pub height: i32,
    pub latest: bool,
}

impl SHUFFLINGModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait SHUFFLINGRepository: Repository<SHUFFLINGModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(SHUFFLINGModel, "SELECT * FROM SHUFFLING WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct PURCHASEPUBLICFEEDBACKModel {
    pub db_id: i64,
    pub id: i64,
    pub public_feedback: String,
    pub height: i32,
    pub latest: bool,
}

impl PURCHASEPUBLICFEEDBACKModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait PURCHASEPUBLICFEEDBACKRepository: Repository<PURCHASEPUBLICFEEDBACKModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(PURCHASEPUBLICFEEDBACKModel, "SELECT * FROM PURCHASE_PUBLIC_FEEDBACK WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct PURCHASEModel {
    pub db_id: i64,
    pub id: i64,
    pub buyer_id: i64,
    pub goods_id: i64,
    pub seller_id: i64,
    pub quantity: i32,
    pub price: i64,
    pub deadline: i32,
    pub note: Vec<u8>,
    pub nonce: Vec<u8>,
    pub timestamp: i32,
    pub pending: bool,
    pub goods: Vec<u8>,
    pub goods_nonce: Vec<u8>,
    pub goods_is_text: bool,
    pub refund_note: Vec<u8>,
    pub refund_nonce: Vec<u8>,
    pub has_feedback_notes: bool,
    pub has_public_feedbacks: bool,
    pub discount: i64,
    pub refund: i64,
    pub height: i32,
    pub latest: bool,
}

impl PURCHASEModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait PURCHASERepository: Repository<PURCHASEModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(PURCHASEModel, "SELECT * FROM PURCHASE WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ASSETTRANSFERModel {
    pub db_id: i64,
    pub id: i64,
    pub asset_id: i64,
    pub sender_id: i64,
    pub recipient_id: i64,
    pub quantity: i64,
    pub timestamp: i32,
    pub height: i32,
}

impl ASSETTRANSFERModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ASSETTRANSFERRepository: Repository<ASSETTRANSFERModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ASSETTRANSFERModel, "SELECT * FROM ASSET_TRANSFER WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct TAGGEDDATAEXTENDModel {
    pub db_id: i64,
    pub id: i64,
    pub extend_id: i64,
    pub height: i32,
    pub latest: bool,
}

impl TAGGEDDATAEXTENDModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait TAGGEDDATAEXTENDRepository: Repository<TAGGEDDATAEXTENDModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(TAGGEDDATAEXTENDModel, "SELECT * FROM TAGGED_DATA_EXTEND WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ACCOUNTCONTROLPHASINGModel {
    pub db_id: i64,
    pub account_id: i64,
    pub whitelist: String,
    pub voting_model: i16,
    pub quorum: Option<i64>,
    pub min_balance: Option<i64>,
    pub holding_id: Option<i64>,
    pub min_balance_model: Option<i16>,
    pub max_fees: Option<i64>,
    pub min_duration: Option<i16>,
    pub max_duration: Option<i16>,
    pub height: i32,
    pub latest: bool,
}

impl ACCOUNTCONTROLPHASINGModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ACCOUNTCONTROLPHASINGRepository: Repository<ACCOUNTCONTROLPHASINGModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ACCOUNTCONTROLPHASINGModel, "SELECT * FROM ACCOUNT_CONTROL_PHASING WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct SHUFFLINGDATAModel {
    pub db_id: i64,
    pub shuffling_id: i64,
    pub account_id: i64,
    pub data: String,
    pub transaction_timestamp: i32,
    pub height: i32,
}

impl SHUFFLINGDATAModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait SHUFFLINGDATARepository: Repository<SHUFFLINGDATAModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(SHUFFLINGDATAModel, "SELECT * FROM SHUFFLING_DATA WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct BIDORDERModel {
    pub db_id: i64,
    pub id: i64,
    pub account_id: i64,
    pub asset_id: i64,
    pub price: i64,
    pub transaction_index: i16,
    pub transaction_height: i32,
    pub quantity: i64,
    pub creation_height: i32,
    pub height: i32,
    pub latest: bool,
}

impl BIDORDERModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait BIDORDERRepository: Repository<BIDORDERModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(BIDORDERModel, "SELECT * FROM BID_ORDER WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ACCOUNTINFOModel {
    pub db_id: i64,
    pub account_id: i64,
    pub name: String,
    pub description: String,
    pub height: i32,
    pub latest: bool,
}

impl ACCOUNTINFOModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ACCOUNTINFORepository: Repository<ACCOUNTINFOModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ACCOUNTINFOModel, "SELECT * FROM ACCOUNT_INFO WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ACCOUNTLEASEModel {
    pub db_id: i64,
    pub lessor_id: i64,
    pub current_leasing_height_from: Option<i32>,
    pub current_leasing_height_to: Option<i32>,
    pub current_lessee_id: Option<i64>,
    pub next_leasing_height_from: Option<i32>,
    pub next_leasing_height_to: Option<i32>,
    pub next_lessee_id: Option<i64>,
    pub height: i32,
    pub latest: bool,
}

impl ACCOUNTLEASEModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ACCOUNTLEASERepository: Repository<ACCOUNTLEASEModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ACCOUNTLEASEModel, "SELECT * FROM ACCOUNT_LEASE WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct CURRENCYMINTModel {
    pub db_id: i64,
    pub currency_id: i64,
    pub account_id: i64,
    pub counter: i64,
    pub height: i32,
    pub latest: bool,
}

impl CURRENCYMINTModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait CURRENCYMINTRepository: Repository<CURRENCYMINTModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(CURRENCYMINTModel, "SELECT * FROM CURRENCY_MINT WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct PUBLICKEYModel {
    pub db_id: i64,
    pub account_id: i64,
    pub public_key: Vec<u8>,
    pub height: i32,
    pub latest: bool,
}

impl PUBLICKEYModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait PUBLICKEYRepository: Repository<PUBLICKEYModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(PUBLICKEYModel, "SELECT * FROM PUBLIC_KEY WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ACCOUNTPROPERTYModel {
    pub db_id: i64,
    pub id: i64,
    pub recipient_id: i64,
    pub setter_id: Option<i64>,
    pub property: String,
    pub value: String,
    pub height: i32,
    pub latest: bool,
}

impl ACCOUNTPROPERTYModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ACCOUNTPROPERTYRepository: Repository<ACCOUNTPROPERTYModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ACCOUNTPROPERTYModel, "SELECT * FROM ACCOUNT_PROPERTY WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ASSETPROPERTYModel {
    pub db_id: i64,
    pub id: i64,
    pub asset_id: i64,
    pub setter_id: i64,
    pub property: String,
    pub value: String,
    pub height: i32,
    pub latest: bool,
}

impl ASSETPROPERTYModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ASSETPROPERTYRepository: Repository<ASSETPROPERTYModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ASSETPROPERTYModel, "SELECT * FROM ASSET_PROPERTY WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct COINTRADEFXTModel {
    pub db_id: i64,
    pub chain_id: i32,
    pub exchange_id: i32,
    pub account_id: i64,
    pub block_id: i64,
    pub height: i32,
    pub timestamp: i32,
    pub exchange_quantity: i64,
    pub exchange_price: i64,
    pub order_id: i64,
    pub order_full_hash: Vec<u8>,
    pub match_id: i64,
    pub match_full_hash: Vec<u8>,
}

impl COINTRADEFXTModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait COINTRADEFXTRepository: Repository<COINTRADEFXTModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(COINTRADEFXTModel, "SELECT * FROM COIN_TRADE_FXT WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct PRUNABLEMESSAGEModel {
    pub db_id: i64,
    pub id: i64,
    pub sender_id: i64,
    pub recipient_id: Option<i64>,
    pub message: Vec<u8>,
    pub message_is_text: bool,
    pub is_compressed: bool,
    pub encrypted_message: Vec<u8>,
    pub encrypted_is_text: Option<bool>,
    pub block_timestamp: i32,
    pub transaction_timestamp: i32,
    pub height: i32,
}

impl PRUNABLEMESSAGEModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait PRUNABLEMESSAGERepository: Repository<PRUNABLEMESSAGEModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(PRUNABLEMESSAGEModel, "SELECT * FROM PRUNABLE_MESSAGE WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct BUYOFFERModel {
    pub db_id: i64,
    pub id: i64,
    pub currency_id: i64,
    pub account_id: i64,
    pub rate: i64,
    pub unit_limit: i64,
    pub supply: i64,
    pub expiration_height: i32,
    pub transaction_height: i32,
    pub creation_height: i32,
    pub transaction_index: i16,
    pub height: i32,
    pub latest: bool,
}

impl BUYOFFERModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait BUYOFFERRepository: Repository<BUYOFFERModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(BUYOFFERModel, "SELECT * FROM BUY_OFFER WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ASKORDERModel {
    pub db_id: i64,
    pub id: i64,
    pub account_id: i64,
    pub asset_id: i64,
    pub price: i64,
    pub transaction_index: i16,
    pub transaction_height: i32,
    pub quantity: i64,
    pub creation_height: i32,
    pub height: i32,
    pub latest: bool,
}

impl ASKORDERModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ASKORDERRepository: Repository<ASKORDERModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ASKORDERModel, "SELECT * FROM ASK_ORDER WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ACCOUNTCURRENCYModel {
    pub db_id: i64,
    pub account_id: i64,
    pub currency_id: i64,
    pub units: i64,
    pub unconfirmed_units: i64,
    pub height: i32,
    pub latest: bool,
}

impl ACCOUNTCURRENCYModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ACCOUNTCURRENCYRepository: Repository<ACCOUNTCURRENCYModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ACCOUNTCURRENCYModel, "SELECT * FROM ACCOUNT_CURRENCY WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct CONTRACTREFERENCEModel {
    pub db_id: i64,
    pub id: i64,
    pub account_id: i64,
    pub contract_name: String,
    pub contract_params: String,
    pub contract_transaction_chain_id: i32,
    pub contract_transaction_full_hash: Vec<u8>,
    pub height: i32,
    pub latest: bool,
}

impl CONTRACTREFERENCEModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait CONTRACTREFERENCERepository: Repository<CONTRACTREFERENCEModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(CONTRACTREFERENCEModel, "SELECT * FROM CONTRACT_REFERENCE WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ACCOUNTLEDGERModel {
    pub db_id: i64,
    pub account_id: i64,
    pub event_type: i16,
    pub event_id: i64,
    pub holding_type: i16,
    pub holding_id: Option<i64>,
    pub change: i64,
    pub balance: i64,
    pub block_id: i64,
    pub height: i32,
    pub timestamp: i32,
}

impl ACCOUNTLEDGERModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ACCOUNTLEDGERRepository: Repository<ACCOUNTLEDGERModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ACCOUNTLEDGERModel, "SELECT * FROM ACCOUNT_LEDGER WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct BALANCEModel {
    pub db_id: i64,
    pub account_id: i64,
    pub balance: i64,
    pub unconfirmed_balance: i64,
    pub height: i32,
    pub latest: bool,
}

impl BALANCEModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait BALANCERepository: Repository<BALANCEModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(BALANCEModel, "SELECT * FROM BALANCE WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct COINORDERFXTModel {
    pub db_id: i64,
    pub id: i64,
    pub account_id: i64,
    pub chain_id: i32,
    pub exchange_id: i32,
    pub full_hash: Vec<u8>,
    pub amount: i64,
    pub quantity: i64,
    pub bid_price: i64,
    pub ask_price: i64,
    pub creation_height: i32,
    pub height: i32,
    pub transaction_height: i32,
    pub transaction_index: i16,
    pub latest: bool,
}

impl COINORDERFXTModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait COINORDERFXTRepository: Repository<COINORDERFXTModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(COINORDERFXTModel, "SELECT * FROM COIN_ORDER_FXT WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ALIASModel {
    pub db_id: i64,
    pub id: i64,
    pub account_id: i64,
    pub alias_name: String,
    pub alias_name_lower: String,
    pub alias_uri: String,
    pub timestamp: i32,
    pub height: i32,
    pub latest: bool,
}

impl ALIASModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ALIASRepository: Repository<ALIASModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ALIASModel, "SELECT * FROM ALIAS WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct TRADEModel {
    pub db_id: i64,
    pub asset_id: i64,
    pub block_id: i64,
    pub ask_order_id: i64,
    pub bid_order_id: i64,
    pub ask_order_height: i32,
    pub bid_order_height: i32,
    pub seller_id: i64,
    pub buyer_id: i64,
    pub is_buy: bool,
    pub quantity: i64,
    pub price: i64,
    pub timestamp: i32,
    pub height: i32,
}

impl TRADEModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait TRADERepository: Repository<TRADEModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(TRADEModel, "SELECT * FROM TRADE WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct HUBModel {
    pub db_id: i64,
    pub account_id: Option<i64>,
    pub min_fee_per_byte: Option<i64>,
    pub uris: String,
    pub height: Option<i32>,
    pub latest: Option<bool>,
}

impl HUBModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait HUBRepository: Repository<HUBModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(HUBModel, "SELECT * FROM HUB WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct EXCHANGEModel {
    pub db_id: i64,
    pub transaction_id: i64,
    pub currency_id: i64,
    pub block_id: i64,
    pub offer_id: i64,
    pub seller_id: i64,
    pub buyer_id: i64,
    pub units: i64,
    pub rate: i64,
    pub timestamp: i32,
    pub height: i32,
}

impl EXCHANGEModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait EXCHANGERepository: Repository<EXCHANGEModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(EXCHANGEModel, "SELECT * FROM EXCHANGE WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ASSETHISTORYModel {
    pub db_id: i64,
    pub id: i64,
    pub full_hash: Vec<u8>,
    pub asset_id: i64,
    pub account_id: i64,
    pub quantity: i64,
    pub timestamp: i32,
    pub chain_id: i32,
    pub height: i32,
}

impl ASSETHISTORYModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ASSETHISTORYRepository: Repository<ASSETHISTORYModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ASSETHISTORYModel, "SELECT * FROM ASSET_HISTORY WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct SCANModel {
    pub rescan: bool,
    pub height: i32,
    pub validate: bool,
}

impl SCANModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait SCANRepository: Repository<SCANModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(SCANModel, "SELECT * FROM SCAN WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ASSETCONTROLPHASINGModel {
    pub db_id: i64,
    pub asset_id: i64,
    pub voting_model: i16,
    pub quorum: Option<i64>,
    pub min_balance: Option<i64>,
    pub holding_id: Option<i64>,
    pub min_balance_model: Option<i16>,
    pub whitelist: String,
    pub expression: String,
    pub sender_property_setter_id: Option<i64>,
    pub sender_property_name: String,
    pub sender_property_value: String,
    pub recipient_property_setter_id: Option<i64>,
    pub recipient_property_name: String,
    pub recipient_property_value: String,
    pub height: i32,
    pub latest: bool,
}

impl ASSETCONTROLPHASINGModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ASSETCONTROLPHASINGRepository: Repository<ASSETCONTROLPHASINGModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ASSETCONTROLPHASINGModel, "SELECT * FROM ASSET_CONTROL_PHASING WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct PEERModel {
    pub address: String,
    pub last_updated: Option<i32>,
    pub services: Option<i64>,
}

impl PEERModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait PEERRepository: Repository<PEERModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(PEERModel, "SELECT * FROM PEER WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct POLLModel {
    pub db_id: i64,
    pub id: i64,
    pub account_id: i64,
    pub name: String,
    pub description: String,
    pub options: String,
    pub min_num_options: Option<i16>,
    pub max_num_options: Option<i16>,
    pub min_range_value: Option<i16>,
    pub max_range_value: Option<i16>,
    pub timestamp: i32,
    pub finish_height: i32,
    pub voting_model: i16,
    pub min_balance: Option<i64>,
    pub min_balance_model: Option<i16>,
    pub holding_id: Option<i64>,
    pub height: i32,
}

impl POLLModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait POLLRepository: Repository<POLLModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(POLLModel, "SELECT * FROM POLL WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct TAGGEDDATATIMESTAMPModel {
    pub db_id: i64,
    pub id: i64,
    pub timestamp: i32,
    pub height: i32,
    pub latest: bool,
}

impl TAGGEDDATATIMESTAMPModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait TAGGEDDATATIMESTAMPRepository: Repository<TAGGEDDATATIMESTAMPModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(TAGGEDDATATIMESTAMPModel, "SELECT * FROM TAGGED_DATA_TIMESTAMP WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct PHASINGPOLLRESULTModel {
    pub db_id: i64,
    pub id: i64,
    pub result: i64,
    pub approved: bool,
    pub height: i32,
}

impl PHASINGPOLLRESULTModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait PHASINGPOLLRESULTRepository: Repository<PHASINGPOLLRESULTModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(PHASINGPOLLRESULTModel, "SELECT * FROM PHASING_POLL_RESULT WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct PHASINGPOLLHASHEDSECRETModel {
    pub db_id: i64,
    pub hashed_secret: Vec<u8>,
    pub hashed_secret_id: i64,
    pub algorithm: i16,
    pub transaction_full_hash: Vec<u8>,
    pub transaction_id: i64,
    pub chain_id: i32,
    pub finish_height: i32,
    pub height: i32,
}

impl PHASINGPOLLHASHEDSECRETModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait PHASINGPOLLHASHEDSECRETRepository: Repository<PHASINGPOLLHASHEDSECRETModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(PHASINGPOLLHASHEDSECRETModel, "SELECT * FROM PHASING_POLL_HASHED_SECRET WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct TAGModel {
    pub db_id: i64,
    pub tag: String,
    pub in_stock_count: i32,
    pub total_count: i32,
    pub height: i32,
    pub latest: bool,
}

impl TAGModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait TAGRepository: Repository<TAGModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(TAGModel, "SELECT * FROM TAG WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct POLLRESULTModel {
    pub db_id: i64,
    pub poll_id: i64,
    pub result: Option<i64>,
    pub weight: i64,
    pub height: i32,
}

impl POLLRESULTModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait POLLRESULTRepository: Repository<POLLRESULTModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(POLLRESULTModel, "SELECT * FROM POLL_RESULT WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct PHASINGVOTEModel {
    pub db_id: i64,
    pub vote_id: i64,
    pub transaction_id: i64,
    pub voter_id: i64,
    pub height: i32,
}

impl PHASINGVOTEModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait PHASINGVOTERepository: Repository<PHASINGVOTEModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(PHASINGVOTEModel, "SELECT * FROM PHASING_VOTE WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ASSETCONTROLPHASINGSUBPOLLModel {
    pub db_id: i64,
    pub asset_id: i64,
    pub name: String,
    pub voting_model: i16,
    pub quorum: Option<i64>,
    pub min_balance: Option<i64>,
    pub holding_id: Option<i64>,
    pub min_balance_model: Option<i16>,
    pub whitelist: String,
    pub sender_property_setter_id: Option<i64>,
    pub sender_property_name: String,
    pub sender_property_value: String,
    pub recipient_property_setter_id: Option<i64>,
    pub recipient_property_name: String,
    pub recipient_property_value: String,
    pub height: i32,
    pub latest: bool,
}

impl ASSETCONTROLPHASINGSUBPOLLModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ASSETCONTROLPHASINGSUBPOLLRepository: Repository<ASSETCONTROLPHASINGSUBPOLLModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ASSETCONTROLPHASINGSUBPOLLModel, "SELECT * FROM ASSET_CONTROL_PHASING_SUB_POLL WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct DATATAGModel {
    pub db_id: i64,
    pub tag: String,
    pub tag_count: i32,
    pub height: i32,
    pub latest: bool,
}

impl DATATAGModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait DATATAGRepository: Repository<DATATAGModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(DATATAGModel, "SELECT * FROM DATA_TAG WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct CURRENCYSUPPLYModel {
    pub db_id: i64,
    pub id: i64,
    pub current_supply: i64,
    pub current_reserve_per_unit_nqt: i64,
    pub height: i32,
    pub latest: bool,
}

impl CURRENCYSUPPLYModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait CURRENCYSUPPLYRepository: Repository<CURRENCYSUPPLYModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(CURRENCYSUPPLYModel, "SELECT * FROM CURRENCY_SUPPLY WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct SELLOFFERModel {
    pub db_id: i64,
    pub id: i64,
    pub currency_id: i64,
    pub account_id: i64,
    pub rate: i64,
    pub unit_limit: i64,
    pub supply: i64,
    pub expiration_height: i32,
    pub transaction_height: i32,
    pub creation_height: i32,
    pub transaction_index: i16,
    pub height: i32,
    pub latest: bool,
}

impl SELLOFFERModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait SELLOFFERRepository: Repository<SELLOFFERModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(SELLOFFERModel, "SELECT * FROM SELL_OFFER WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct UNCONFIRMEDTRANSACTIONModel {
    pub db_id: i64,
    pub id: i64,
    pub expiration: i32,
    pub transaction_height: i32,
    pub fee_per_byte: i64,
    pub arrival_timestamp: i64,
    pub transaction_bytes: Vec<u8>,
    pub height: i32,
    pub prunable_json: String,
}

impl UNCONFIRMEDTRANSACTIONModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait UNCONFIRMEDTRANSACTIONRepository: Repository<UNCONFIRMEDTRANSACTIONModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(UNCONFIRMEDTRANSACTIONModel, "SELECT * FROM UNCONFIRMED_TRANSACTION WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ACCOUNTGUARANTEEDBALANCEModel {
    pub db_id: i64,
    pub account_id: i64,
    pub additions: i64,
    pub height: i32,
}

impl ACCOUNTGUARANTEEDBALANCEModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ACCOUNTGUARANTEEDBALANCERepository: Repository<ACCOUNTGUARANTEEDBALANCEModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ACCOUNTGUARANTEEDBALANCEModel, "SELECT * FROM ACCOUNT_GUARANTEED_BALANCE WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ASSETDIVIDENDModel {
    pub db_id: i64,
    pub id: i64,
    pub asset_id: i64,
    pub amount: i64,
    pub dividend_height: i32,
    pub total_dividend: i64,
    pub num_accounts: i64,
    pub timestamp: i32,
    pub height: i32,
}

impl ASSETDIVIDENDModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ASSETDIVIDENDRepository: Repository<ASSETDIVIDENDModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ASSETDIVIDENDModel, "SELECT * FROM ASSET_DIVIDEND WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct CURRENCYFOUNDERModel {
    pub db_id: i64,
    pub currency_id: i64,
    pub account_id: i64,
    pub amount: i64,
    pub height: i32,
    pub latest: bool,
}

impl CURRENCYFOUNDERModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait CURRENCYFOUNDERRepository: Repository<CURRENCYFOUNDERModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(CURRENCYFOUNDERModel, "SELECT * FROM CURRENCY_FOUNDER WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ASSETDELETEModel {
    pub db_id: i64,
    pub id: i64,
    pub asset_id: i64,
    pub account_id: i64,
    pub quantity: i64,
    pub timestamp: i32,
    pub height: i32,
}

impl ASSETDELETEModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ASSETDELETERepository: Repository<ASSETDELETEModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ASSETDELETEModel, "SELECT * FROM ASSET_DELETE WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct PHASINGPOLLVOTERModel {
    pub db_id: i64,
    pub transaction_id: i64,
    pub voter_id: i64,
    pub height: i32,
}

impl PHASINGPOLLVOTERModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait PHASINGPOLLVOTERRepository: Repository<PHASINGPOLLVOTERModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(PHASINGPOLLVOTERModel, "SELECT * FROM PHASING_POLL_VOTER WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct SHUFFLINGPARTICIPANTModel {
    pub db_id: i64,
    pub shuffling_id: i64,
    pub account_id: i64,
    pub next_account_id: Option<i64>,
    pub participant_index: i16,
    pub state: i16,
    pub blame_data: String,
    pub key_seeds: String,
    pub data_transaction_full_hash: Vec<u8>,
    pub height: i32,
    pub latest: bool,
}

impl SHUFFLINGPARTICIPANTModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait SHUFFLINGPARTICIPANTRepository: Repository<SHUFFLINGPARTICIPANTModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(SHUFFLINGPARTICIPANTModel, "SELECT * FROM SHUFFLING_PARTICIPANT WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct TAGGEDDATAModel {
    pub db_id: i64,
    pub id: i64,
    pub account_id: i64,
    pub name: String,
    pub description: String,
    pub tags: String,
    pub parsed_tags: String,
    #[sqlx(rename = "TYPE")]
    pub type_: String,
    pub data: Vec<u8>,
    pub is_text: bool,
    pub filename: String,
    pub channel: String,
    pub block_timestamp: i32,
    pub transaction_timestamp: i32,
    pub height: i32,
    pub latest: bool,
}

impl TAGGEDDATAModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait TAGGEDDATARepository: Repository<TAGGEDDATAModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(TAGGEDDATAModel, "SELECT * FROM TAGGED_DATA WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct REFERENCEDTRANSACTIONModel {
    pub db_id: i64,
    pub transaction_id: i64,
    pub referenced_transaction_id: i64,
}

impl REFERENCEDTRANSACTIONModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait REFERENCEDTRANSACTIONRepository: Repository<REFERENCEDTRANSACTIONModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(REFERENCEDTRANSACTIONModel, "SELECT * FROM REFERENCED_TRANSACTION WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct VOTEModel {
    pub db_id: i64,
    pub id: i64,
    pub poll_id: i64,
    pub voter_id: i64,
    pub vote_bytes: Vec<u8>,
    pub height: i32,
}

impl VOTEModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait VOTERepository: Repository<VOTEModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(VOTEModel, "SELECT * FROM VOTE WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ACCOUNTFXTModel {
    pub id: i64,
    pub balance: Vec<u8>,
    pub height: i32,
}

impl ACCOUNTFXTModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ACCOUNTFXTRepository: Repository<ACCOUNTFXTModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ACCOUNTFXTModel, "SELECT * FROM ACCOUNT_FXT WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct CURRENCYTRANSFERModel {
    pub db_id: i64,
    pub id: i64,
    pub currency_id: i64,
    pub sender_id: i64,
    pub recipient_id: i64,
    pub units: i64,
    pub timestamp: i32,
    pub height: i32,
}

impl CURRENCYTRANSFERModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait CURRENCYTRANSFERRepository: Repository<CURRENCYTRANSFERModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(CURRENCYTRANSFERModel, "SELECT * FROM CURRENCY_TRANSFER WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct ALIASOFFERModel {
    pub db_id: i64,
    pub id: i64,
    pub price: i64,
    pub buyer_id: Option<i64>,
    pub height: i32,
    pub latest: bool,
}

impl ALIASOFFERModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait ALIASOFFERRepository: Repository<ALIASOFFERModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(ALIASOFFERModel, "SELECT * FROM ALIAS_OFFER WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct CURRENCYModel {
    pub db_id: i64,
    pub id: i64,
    pub account_id: i64,
    pub name: String,
    pub name_lower: String,
    pub code: String,
    pub description: String,
    #[sqlx(rename = "TYPE")]
    pub type_: i32,
    pub initial_supply: i64,
    pub reserve_supply: i64,
    pub max_supply: i64,
    pub creation_height: i32,
    pub issuance_height: i32,
    pub min_reserve_per_unit_nqt: i64,
    pub min_difficulty: i16,
    pub max_difficulty: i16,
    pub ruleset: i16,
    pub algorithm: i16,
    pub decimals: i16,
    pub height: i32,
    pub latest: bool,
}

impl CURRENCYModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait CURRENCYRepository: Repository<CURRENCYModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(CURRENCYModel, "SELECT * FROM CURRENCY WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct GOODSModel {
    pub db_id: i64,
    pub id: i64,
    pub seller_id: i64,
    pub name: String,
    pub description: String,
    pub parsed_tags: String,
    pub tags: String,
    pub timestamp: i32,
    pub quantity: i32,
    pub price: i64,
    pub delisted: bool,
    pub height: i32,
    pub latest: bool,
    pub has_image: bool,
}

impl GOODSModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait GOODSRepository: Repository<GOODSModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(GOODSModel, "SELECT * FROM GOODS WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct PHASINGPOLLModel {
    pub db_id: i64,
    pub id: i64,
    pub account_id: i64,
    pub whitelist_size: i16,
    pub finish_height: i32,
    pub voting_model: i16,
    pub quorum: Option<i64>,
    pub min_balance: Option<i64>,
    pub holding_id: Option<i64>,
    pub min_balance_model: Option<i16>,
    pub hashed_secret: Vec<u8>,
    pub algorithm: Option<i16>,
    pub height: i32,
}

impl PHASINGPOLLModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait PHASINGPOLLRepository: Repository<PHASINGPOLLModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(PHASINGPOLLModel, "SELECT * FROM PHASING_POLL WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}

#[derive(Debug, Clone, PartialEq, sqlx::FromRow, Serialize, Deserialize)]
pub struct EXCHANGEREQUESTModel {
    pub db_id: i64,
    pub id: i64,
    pub account_id: i64,
    pub currency_id: i64,
    pub units: i64,
    pub rate: i64,
    pub is_buy: bool,
    pub timestamp: i32,
    pub height: i32,
}

impl EXCHANGEREQUESTModel {
    pub fn to_domain(&self) -> Result<Block, BlockchainError> {
        unimplemented!()
    }

    pub fn from_domain(_block: &Block) -> Result<Self, BlockchainError> {
        unimplemented!()
    }
}

#[async_trait]
pub trait EXCHANGEREQUESTRepository: Repository<EXCHANGEREQUESTModel> {
    async fn find_by_id(conn: &DbConnection, id: i64) -> sqlx::Result<Option<Self>> {
        sqlx::query_as!(EXCHANGEREQUESTModel, "SELECT * FROM EXCHANGE_REQUEST WHERE db_id = ?", id)
            .fetch_optional(conn)
            .await
    }
}


#[cfg(test)]
mod generated_model_tests {
    use super::*;
    use chrono::Utc;
    use serde_json::json;

}

